### ISSUE TITLE
Colour contrast is too low

### ISSUE THREAD

**Issue by jkshapiro** [dadederk/dadederk.github.io#1]
I came to this site to read https://dadederk.github.io/post/2021-01-21-01/, a post about accessibility, but ironically the colours used make the post itself inaccessible. Please see https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast

**Comment by dadederk** [comment]
Hi @jkshapiro. Thanks for bringing this up. Not to serve as an excuse but I'm not a web developer and was just using the default configuration of a Hugo theme. I've manage to find how to change the text color and it should now meet color contrast requirements. Will try to spend more time doing this template more accessible asap. Thank you.
